#!/bin/bash
#
# tar file generator for navigation system
# Copyright Sterwen Technology 2021-2022
#
tar cvf navigation.tar src/*.py src/*/*.py conf/*.yml def/* *.service *.py LICENSE run_server install_server
