#!/bin/bash
# nmea_router protobuf and gRPC

input_dir=src/protobuf
output_dir=src/generated

gen_protobuf() {
  echo "processing:$1"
  input_file=${input_dir}/"$1.proto"
  python -m grpc_tools.protoc -I ./${input_dir} --python_out=./${output_dir} --grpc_python_out=./${output_dir} ${input_file}
  output_file=${output_dir}/"$1_pb2_grpc.py"
  if [ -e ${output_file} ]
  then
    shift
    python mod_pb2.py ${output_file} generated $*
  fi
}

adjust_protobuf() {
  echo "adjusting:$1"
  process_file=${output_dir}/"$1_pb2.py"
  shift
  python mod_pb2.py "${process_file}" generated $*
}

gen_protobuf vedirect
gen_protobuf console
gen_protobuf nmea0183
gen_protobuf nmea2000
gen_protobuf nmea_messages
gen_protobuf input_server nmea_messages nmea2000
gen_protobuf nmea_server
gen_protobuf agent
gen_protobuf arguments
gen_protobuf ecu
gen_protobuf nmea2000_classes_gen
adjust_protobuf input_server nmea_messages
adjust_protobuf nmea_messages nmea0183 nmea2000
adjust_protobuf nmea_server nmea_messages
adjust_protobuf console arguments
adjust_protobuf ecu nmea2000