#!/bin/bash
#
# tar file generator for navigation system
# Copyright Sterwen Technology 2021-2024
#

tar cvf navigation.tar src/*.py src/*/*.py conf/*.yml def/* *.service *.py LICENSE run_server install_server \
  requirements.txt can_setup install_can
