//-------------------------------------------------------------------------------
// Name:        vedirect.proto
// Purpose:     Victron RS485 messages protobuf definition file
//
// Author:      Laurent Carré
//
// Created:     18/02/2022
// Copyright:   (c) Laurent Carré Sterwen Technology 2021-2026
// Licence:     Eclipse Public License 2.0
//-------------------------------------------------------------------------------

syntax = "proto3";

// import "arguments.proto";

// Messages to transmit Victron VE direct messages between the reader and the instrument

enum VE_Error{
  no_error=0;
  Battery_voltage_too_high=2;
  Bulk_time_limit_exceeded=20;
  Current_sensor_issue=21;
  Input_voltage_too_high=33;
  Input_current_too_high=34;
}

enum VE_state {
  Off=0;
  Low_power=1; // not used by MPPT
  Fault=2;
  Bulk=3;
  Absorption=4;
  Float=5;
  Storage=6;
  Equalize=7;
  Starting_up=245;
  Repeated_absorption=246;
  Auto_equalize=247;
  External_control=252;
}

enum VE_MPPT {
  MPPT_Off=0;
  Limited=1;
  Active=2;
}

// Global messages

message energy_request {
  uint32 id=1;      // request ID
  string command=2;         // Optional - Additional command
  uint32 trend_samples=3;   // Optional -  Max number of samples to be returned
}

message VE_Hex_Parameter {
  string  name=1;     // short name used as dictionary entry
  string description=2; // full description as per documentation
  uint32 register=3;    //
}

// MPPT - Solar panel specific section

message MPPT_device {
  // Semi static information
  uint32 id=1;            // device ID - identify the device when more than one are used
  bool communication_ok=14;  // True if the communication is working with the MPPT device
  string device_label=12;
  string  device_model=13;
  string product_id = 2;
  string firmware = 3;
  string serial = 10;
  VE_Error error =4;
  VE_state state=5;
  VE_MPPT mppt_state =7;
  float day_max_power = 6;  //Watt
  float day_power = 8;      //kilo Watt-heure
  string msg_timestamp = 9; // ISO UTC
  MPPT_parameters parameters = 11;  // Optional
}

message MPPT_parameters {
  uint32 instance=6;          // Instance ID of the MPPT device
  uint32 battery=7;           // Instance ID of the battery bank charged by the MPPT
  float panel_max_power=1;    // Watt
  float panel_max_voltage=2;  // Volt
  float max_voltage=3;        // Volt - on MPPT output
  float trend_duration=4;     // Duration in minutes of the trand series
  float trend_interval=5;     // interval in seconds between trend values
}

message solar_output {
  float current = 1;  // Amp
  float voltage =2;   // Volt
  float panel_voltage=4;  // Volt
  float panel_power =3;  //Watt
}

message solar_trend_response {
  int32 id=1;
  int32 nb_values=2;
  float interval=3;
  repeated solar_output values=4;
}

service MPPTService {
  // returns semi-static information + parameters with the 'parameters' command
  rpc GetDeviceInfo(energy_request) returns (MPPT_device) {}
  rpc GetOutput(energy_request) returns (solar_output) {}
  rpc GetTrend(energy_request) returns (solar_trend_response) {}
}

// Battery bank service

message ShuntDevice {
  string product_id = 2;
  string firmware = 3;
  string serial = 10;
  VE_Error error =4;
  VE_state state=5;
}

message BatteryBank {
  uint32 instance=1;
  string label=2;
  string chemistry=11;
  float nominal_voltage=3;    // Volt
  float nominal_capacity=4;   // Wh
  float voltage=5;            // Actual voltage
  float state_of_charge=6;    // Percent
  float max_voltage=7;        // Maximum charge voltage => alarm
  float min_voltage=8;        // Minimum operating voltage => alarm
  float charge_voltage=9;     // Bulk charge
  float max_charge_current=10; // A
  float last_24h_energy=12;   // Wh Positive charge
  float reporting_interval=13; // In seconds
}

message battery_in_out {
  float voltage = 1;  // Instant voltage
  float current = 2;  // Instant current positive = charge, negative discharge
  float energy_variation = 3; // Wh positive = charge
}

message battery_trend_bucket {
  string timestamp=1;  // ISO UTC of the reporting period end
  float voltage=2;     // Voltage at the end of the period
  float energy_variation=3;      // in Wh positive charge - Variation during the interval
  float state_of_charge=4;    // Percent at the end of the period
}

message battery_trend_response {
  uint32 id=1;
  uint32 nb_values=2;   // Number of values in the response
  float interval=3;     // Interval between samples in seconds
  repeated battery_trend_bucket samples=4;
}

service BatteryService {
    rpc GetInformation(energy_request) returns (BatteryBank) {}
    rpc GetValues(energy_request) returns (battery_in_out) {}
    rpc GetTrend(energy_request) returns (battery_trend_response) {}
    }

// DC-DC Charger


