//-------------------------------------------------------------------------------
// Name:        nmea2000_service.proto
// Purpose:     protobuf and grpc for NMEA2000 server data streams
//
// Author:      Laurent Carré
//
// Created:     12/06/2022
// Copyright:   (c) Laurent Carré Sterwen Technology 2021-2026
// Licence:     Eclipse Public License 2.0
//-------------------------------------------------------------------------------

syntax = "proto3";

import "iso_name.proto";
import "nmea2000_classes_iso_gen.proto";
import "nmea2000.proto";
import "nmea_messages.proto";

message PGN_statistic {
  uint32 pgn=1;     // PGN emitted
  uint32 count=2;   // number of occurrence since the device is seen
}

message PGN_definition {
  uint32 pgn=1;
  string definition=2;
}

// Message representing CAN/NMEA2000 device
message N2KDeviceMsg {
  uint32 address=1;       // CAN address 0-253
  bool changed=2;         // True if the device has changed or has appeared since last call to the server
  bool is_proxy=7;        // indicate that the device is local or not to the CAN controller
  float last_time_seen=3; // Epoch seconds
  ISOName iso_name=4;     // Unique identifier of the Device  see J1939
  Pgn126996ClassPb product_information=5;       // NMEA2000 PGN126996 content
  Pgn126998ClassPb configuration_information=6; // NMEA2000 PGN126998 content
  repeated PGN_statistic stats=8;
  repeated PGN_statistic out_stats=9;
}

message Nmea2000ControllerMsg {
  string channel=1;
  string status = 2;
  float incoming_rate = 3;
  float outgoing_rate = 4;
  bool traces_on=5;
  repeated N2KDeviceMsg devices=6;    // All devices seen by the controller
}

message Nmea2000Request{
  uint32 id = 1;
  string cmd = 2;
  uint32 device = 3;
  uint32 pgn=4;
}

message Nmea2000Ack {
  uint32 id=1;
  uint32 messages_count=2;
  uint32 error=3;
}

//
message Nmea2000ReadRequest{
  uint32 id=1;
  string client=2;  // client identification
  repeated uint32 select_sources=3; // only the selected sources will be forwarded if empty or equal to 255 all sources are selected
  repeated uint32 reject_sources=4; // all sources from the list are rejected
  repeated uint32 select_pgn=5; // only the PGN in the list are forwarded if the list is empty all PGN are forwarded
  repeated uint32  reject_pgn=6; //PGN in the list are rejected
}

message Nmea2000SendRequest {
  uint32 id=1;
  string device=2;  // that is the device name that shall send the message. Shall be created on the CAN server in the configuration file
  nmea2000pb n2k_msg = 3;  // that is the actual message (encoded) to be sent
}

service Nmea2000ControllerService {
  rpc GetStatus(Nmea2000Request) returns (Nmea2000ControllerMsg) {}
  rpc GetDeviceStatus(Nmea2000Request) returns (N2KDeviceMsg) {}
  rpc GetPgnDefinition(Nmea2000Request) returns (PGN_definition) {}
  rpc StartTrace(Nmea2000Request) returns (Nmea2000ControllerMsg) {}
  rpc StopTrace(Nmea2000Request) returns (Nmea2000ControllerMsg) {}
  rpc ReadNmea2000Msg(Nmea2000ReadRequest) returns (stream nmea2000pb) {}
  rpc SendNmea2000Msg(Nmea2000SendRequest) returns (Nmea2000Ack) {}
  rpc SendNmea2000Stream(stream nmea2000pb) returns (server_resp) {}
}