#!/bin/bash

# Vérifie qu'un répertoire est fourni en argument
# On utilise the contenu de NAVIGATION_HOME par défaut
if [ -z "${NAVIGATION_HOME+x}" ]; then
# pas de variable d'environnement
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <répertoire>"
    exit 1
else
    # Répertoire de départ
    DIR="$1"
fi
else
    DIR="$NAVIGATION_HOME/navigation_server"
fi

# Vérifie que le répertoire existe
if [ ! -d "$DIR" ]; then
    echo "Erreur: Le répertoire '$DIR' n'existe pas."
    exit 1
fi

# Supprime les fichiers .pyc, .pyo, .pyd
find "$DIR" -type f \( -name "*.pyc" -o -name "*.pyo" -o -name "*.pyd" \) -delete

# Supprime les répertoires __pycache__
find "$DIR" -type d -name "__pycache__" -exec rm -rf {} +

echo "Nettoyage terminé : fichiers compilés et répertoires __pycache__ supprimés dans '$DIR'."