#!/bin/bash
if [ ! -v NAVIGATION_HOME ]
then
  echo "Environment variable NAVIGATION_HOME is missing"
  exit
fi
cd "$NAVIGATION_HOME" || exit
# first generate the protobuf
python gen_code.py -pb -c iso -o nmea2000_classes_iso_gen
python gen_code.py -pb -c data -o nmea2000_classes_gen
# now generate the protobuf python
./develop/gen_proto
# en finally generate the NMEA2000 python
python gen_code.py -py -cv -c iso -o nmea2000_classes_iso_gen
python gen_code.py -py -cv -c data -o nmea2000_classes_gen
