#!/bin/bash
# nmea_router protobuf and gRPC
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2025
# Licence:     Eclipse Public License 2.0

if [ ! -v NAVIGATION_HOME ]
then
  echo "Environment variable NAVIGATION_HOME is missing"
  exit
fi
PACKAGE="navigation_server"
input_dir="$NAVIGATION_HOME/$PACKAGE/protobuf"
output_dir="$NAVIGATION_HOME/$PACKAGE/generated"
cd "$NAVIGATION_HOME/develop" || exit

gen_protobuf() {
  echo "generating protobuf for:$1"
  input_file=${input_dir}/"$1.proto"
  python -m grpc_tools.protoc -I ${input_dir} --python_out=${output_dir} --grpc_python_out=${output_dir} ${input_file}
  output_file=${output_dir}/"$1_pb2_grpc.py"
  if [ -e ${output_file} ]
  then
    # shift
    python mod_pb2.py ${output_file} "$PACKAGE.generated" "$@"
  fi
}

adjust_protobuf() {
  echo "adjusting:$1"
  process_file=${output_dir}/"$1_pb2.py"
  # shift
  python mod_pb2.py "${process_file}" "$PACKAGE.generated" "$@"
}

gen_protobuf energy
gen_protobuf console
gen_protobuf nmea0183
gen_protobuf nmea2000
gen_protobuf nmea_messages
gen_protobuf input_server nmea_messages nmea2000
gen_protobuf nmea_server nmea_messages
gen_protobuf agent
gen_protobuf arguments
gen_protobuf uuid
gen_protobuf ecu
gen_protobuf nmea2000_classes_iso_gen
gen_protobuf nmea2000_classes_gen
gen_protobuf iso_name
gen_protobuf navigation_data
gen_protobuf navigation_objects
gen_protobuf gnss nmea_messages nmea2000
adjust_protobuf input_server nmea_messages nmea2000
adjust_protobuf nmea_messages nmea0183 nmea2000
adjust_protobuf nmea_server nmea_messages
adjust_protobuf console arguments iso_name nmea2000_classes_iso_gen
adjust_protobuf ecu nmea2000
adjust_protobuf energy arguments
adjust_protobuf navigation_objects uuid
adjust_protobuf gnss nmea_messages nmea2000
