#!/bin/bash
# perform can initialisation commands - assumed to be run a root
# on STNC hard setup for GPIO
gpioset --mode=wait gpiochip2 26=0 &
gpioset --mode=wait gpiochip2 27=0 &
/sbin/ip link set can0 up type can bitrate 250000
/sbin/ip link set can1 up type can bitrate 250000
