#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     09/07/2024
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
function: Navigation message server
log_level: INFO
trace_dir: /data/solidsense
log_module:
    nmea2000.nmea2k_filters: INFO
    router_core.filters: INFO
    router_core.publisher: INFO
    couplers.shipmodul_if: INFO


features:
    - router_core
    - nmea2000
    - nmea0183
    - couplers:
          - ShipModulConfig
          - ShipModulInterface
          - InternalGps
          - MpptCoupler
          - NMEATCPReader

servers:

- Main:
      class: NavigationMainServer
      
- NMEAServer:
    class: NMEAServer
    port: 4500
    nmea2000: dyfmt
    filters: [DiscardAISGPS, RemoveGPS, AutoPilotN2K, Barometer]
    
- gRPCMain:
    class: GrpcServer
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    coupler: MiniPlex3
    
- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: MiniPlex3
    max_silent: 10
    # master: 172.16.0.100
    timeout: 8.0
    nmea2000: dyfmt
    
- NMEANetwork:
    class: NMEA2KController
    max_silent: 70.0


couplers:

- MiniPlex3:
    class: ShipModulInterface
    address: 172.16.2.100
    port: 10110
    transport: TCP
    nmea2000_controller: NMEANetwork
    protocol: nmea2000
    autostart: true
    trace_raw: false
    


- Gps:
   class: InternalGps
   autostart: false
    
- ScannavReplay:
    class: NMEATCPReader
    address: 172.16.1.103
    port: 2000
    autostart: false
    
services:

- Console:
    class: Console
    server: gRPCMain


publishers:

- SendNMEA2000:
    class: GrpcPublisher
    active: true
    decode_nmea2000: false
    nmea0183: convert_strict
    address: 127.0.0.1
    port: 4508
    max_retry: 0
    filters: [Engine]
    couplers: [MiniPlex3]

filters:

- RemoveGPS:
     class: NMEA0183Filter
     talker: GP
     formatter: GSV
     type: discard

- DiscardAISGPS:
     class: NMEA2000Filter
     source: 43
     pgn: [129025, 129026]
     type: discard

- AutoPilotN2K:
    class: NMEA2000Filter
    source: 7
    type: discard

- Barometer:
    class: NMEA2000TimeFilter
    source: 52
    pgn: [130310, 130311, 130314]
    type: select
    period: 10.0

- Engine:
    class: NMEA2000Filter
    pgn: [127488, 127489]
    type: select
      
