# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nmea0183.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enmea0183.proto\"=\n\x08nmea0183\x12\x0e\n\x06talker\x18\x01 \x01(\t\x12\x11\n\tformatter\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\tb\x06proto3')



_NMEA0183 = DESCRIPTOR.message_types_by_name['nmea0183']
nmea0183 = _reflection.GeneratedProtocolMessageType('nmea0183', (_message.Message,), {
  'DESCRIPTOR' : _NMEA0183,
  '__module__' : 'nmea0183_pb2'
  # @@protoc_insertion_point(class_scope:nmea0183)
  })
_sym_db.RegisterMessage(nmea0183)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NMEA0183._serialized_start=18
  _NMEA0183._serialized_end=79
# @@protoc_insertion_point(module_scope)
