# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nmea2000_pb2 as nmea2000__pb2
import nmea0183_pb2 as nmea0183__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x1a\x0enmea2000.proto\x1a\x0enmea0183.proto\"S\n\x08nmea_msg\x12\x1c\n\x07N2K_msg\x18\x01 \x01(\x0b\x32\t.nmea2000H\x00\x12\x1e\n\tN0183_msg\x18\x02 \x01(\x0b\x32\t.nmea0183H\x00\x42\t\n\x07Message2\x12\n\x10NavigationServerb\x06proto3')



_NMEA_MSG = DESCRIPTOR.message_types_by_name['nmea_msg']
nmea_msg = _reflection.GeneratedProtocolMessageType('nmea_msg', (_message.Message,), {
  'DESCRIPTOR' : _NMEA_MSG,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:nmea_msg)
  })
_sym_db.RegisterMessage(nmea_msg)

_NAVIGATIONSERVER = DESCRIPTOR.services_by_name['NavigationServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NMEA_MSG._serialized_start=48
  _NMEA_MSG._serialized_end=131
  _NAVIGATIONSERVER._serialized_start=133
  _NAVIGATIONSERVER._serialized_end=151
# @@protoc_insertion_point(module_scope)
